# set up the default terminal
ENV["TERM"]="linux"

Vagrant.configure("2") do |config|
  
  # set the image for the vagrant box
  config.vm.box = "opensuse/Leap-15.2.x86_64"
  ## Set the image version
  # config.vm.box_version = "15.2.31.247"

  # st the static IP for the vagrant box
  config.vm.network "private_network", ip: "192.168.56.4"
  
  # configure the parameters for VirtualBox provider
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "4096"
    vb.cpus = 4
    vb.customize ["modifyvm", :id, "--ioapic", "on"]
  end

  # Folder Settings
  # config.vm.synced_folder ".", "/project", create: true
  
  # Provision Settings
  config.vm.provision "shell", inline: <<-SHELL
    sudo zypper -y update 
    sudo zypper -y dist-upgrade
    sudo zypper in -y git-core
    git --version
    sudo zypper install -y python3-pip
    sudo pip install --upgrade pip
    hash -r
    pip --version; pip3 --version
    cd project/techtrends
    sudo pip3 install -r requirements.txt
  SHELL

end
