---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: techtrends-prod
  namespace: argocd
spec:
  project: default
  source:
    chart: techtrends
    helm:
      valueFiles:
      - "values-prod.yaml"
      path: /project/helm/
    repoURL: https://github.com/atm8119/nd064_course_1/tree/main/project/helm
    targetRevision: HEAD
  destination:
    namespace: default
    server: https://kubernetes.default.svc
