---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: techtrends-staging
  namespace: argocd
spec:
  project: default
  source:
    chart: techtrends
    helm:
      parameters:
        - name: values
          value: "values-staging.yaml"
    repoURL: https://github.com/atm8119/nd064_course_1/tree/main/project/helm
    targetRevision: 1.0.0
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
