## Set the API endpoint used to create the Deployment resource.
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: techtrends
  name: techtrends
  namespace: sandbox
## Define the desired configuration for the Deployment resource.
spec:
  ## Set the number of replicas.
  replicas: 1
  ## Identify the pods managed by this Deployment using the following selectors.
  selector:
    matchLabels:
      app: techtrends
  ## Set the RollingOut strategy for the Deployment.
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  ## Set the configuration for the pods.
  template:
    ## Define the identifiable metadata for the pods.
    metadata:
      labels:
        app: techtrends
    ## Define the desired state of the pod configuration.
    spec:
      containers:
      - image: techtrends:latest
        imagePullPolicy: IfNotPresent
        name: techtrends
        ## Expose the port the container is listening on.
        ports:
        - containerPort: 3111
          protocol: TCP
        ## Define the rules for the liveness probes.
        ## If the application is not responsive, then the pod will be restarted automatically. 
        livenessProbe:
           httpGet:
             path: /healthz
             port: 3111
        ## Define the rules for the readiness probes.
        ## If the application is responsive, then traffic will be sent to this pod.
        readinessProbe:
           httpGet:
             path: /healthz
             port: 3111
        ## Set the resource requests and limits for an application.
        resources:
        ## Resource allocations per pod. 'Mi' = Mebibytes. 'm' = miliCPUs.
          requests:
            memory: "64Mi"
            cpu: "250m"
        ## Resource consumption limits per pod. 'Mi' = Mebibytes. 'm' = miliCPUs.
          limits:
            memory: "128Mi"
            cpu: "500m"
