namespace:
  name: staging

## overwrite service values in service.yaml
service:
  port: 5111

## overwrite deployment values in deploy.yaml
# set the number of replicas for an application 
replicaCount: 3

resources:
  # resource allocations per pod. 'Mi' = Mebibytes. 'm' = miliCPUs.
  requests:
    memory: "90Mi"
    cpu: "300m"
  # resource consumption limits per pod. 'Mi' = Mebibytes. 'm' = miliCPUs.
  limits:
    memory: "128Mi"
    cpu: "500m"
