namespace:
  name: sandbox

## set default service values in service.yaml
service:
  port: 4111
  protocol: TCP
  targetPort: 3111
  type: ClusterIP

## set default deployment values in deploy.yaml
# define the image to execute with the Deployment 
image:
  repository: alonsotm/techtrends
  tag: latest
  pullPolicy: IfNotPresent

# set the number of replicas for an application 
replicaCount: 1

resources:
  # Resource allocations per pod. 'Mi' = Mebibytes. 'm' = miliCPUs.
  requests:
    memory: "64Mi"
    cpu: "250m"
  # Resource consumption limits per pod. 'Mi' = Mebibytes. 'm' = miliCPUs.
  limits:
    memory: "128Mi"
    cpu: "500m"

# set container port for deployment
containerPort: 3111

# set liveness probe path using containerPort
livenessProbe:
  path: /healthz
# set readiness probe path using containerPort
readinessProbe:
  path: /healthz