## file location and name: # .github/workflows/techtrends-dockerhub.yml
name: TechTrends - Package with Docker
## Set the trigger policy.
## In this case, the workflow is execute on a `push` event,
## or when a new commit is pushed to the repository
on:
  push:
    branches: 
      - 'main'
    # paths:
    #   - 'techtrends/**'
## Workflow steps list
jobs:
  check-python-version:
    ## Configure the operating system the workflow should run on.
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./project
          file: ./techtrends/Dockerfile
          push: true
          tags: alonsotm/techtrends:latest
